version: '3.8'
services:
  dev-db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest
    ports:
      - '5434:5434'

  mysql-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    expose:
      - '3306'

  test-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_PASSWORD: password
    ports:
      - '3307:3306'
    expose:
      - '3306'
